# Generated by Django 3.0.2 on 2020-01-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('adress_line1', models.CharField(max_length=30)),
                ('adress_line2', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=10)),
                ('restock_date', models.DateTimeField(verbose_name='date restocked')),
                ('restock_amount', models.IntegerField(max_length=10)),
                ('left_in_stock', models.IntegerField(max_length=10)),
                ('dimensions', models.CharField(max_length=20)),
                ('weight', models.IntegerField(max_length=10)),
                ('packaging_type', models.CharField(choices=[('FC', 'Folding carton'), ('RB', 'Rigid box'), ('SB', 'Shoulder box'), ('CB', 'Collapsible box'), ('CCB', 'Corrugated cardboard box')], default='FC', max_length=3)),
            ],
        ),
    ]
