# Generated by Django 3.0.2 on 2020-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='left_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
