# Generated by Django 3.0.2 on 2020-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0002_auto_20200111_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restock_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
