# Generated by Django 3.0.2 on 2020-01-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='left_in_stock',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='restock_amount',
            field=models.IntegerField(default=40),
        ),
    ]
